### ISSUE TITLE
Experiment with log-log plot of recent changes

### ISSUE THREAD

**Issue by davidbau** [davidbau/covid-19-chart#12]
Idea from here, https://www.youtube.com/watch?v=54XLXg4fYsc

This idea should probably be plotted on a different webpage.

The idea of this plot is to understand whether a locality is still on the exponential domain or if we have succeeded in leaving it (or if we are resuming it).  The idea is to plot log(recent changes) on the y axis versus log(less-recent changes) on the x axis.  While we're on exponential growth, this will be on the line given by the exponent, but will quickly depart when not.

The youtube video described graphing log(weekly change) vs log(total cumulative) - but maybe having both sides be a delta would be able to show when (e.g., in Japan) exponential growth restarts after the society resumes social behavior too early.

**Comment by davidbau** [comment]
@davidebbo if this is interesting to you, I think it would be cool to see on a per-state basis.

https://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type

**Comment by davidebbo** [comment]
Ok, I will look at this next weekend. Why do you think it should go on a different page? Isn't it essentially about plotting the same data in yet a different way?

**Comment by davidbau** [comment]
No you're right, maybe it should be on the same page.

**Comment by davidebbo** [comment]
Hoping to look at this as a weekend project. But looking at chartist, I'm not sure how easily it will support this because:

- It only appears to support log scale on the y axis and not x axis
- It doesn't seem to support graphing arbitrary points. i.e. here I think we basically have a sequence of arbitrary (x,y) points, instead of the chartist model of passing an array of 'y' value, where 'x' is assumed to be the array index

Or am I looking at this the wrong way? Obviously, there is the option of moving to a different graphing solution, but that's kind of a big move!

**Comment by davidbau** [comment]
Yeah let's see if it can be done within chartist for now.

I think it's an issue of documentation - very few examples show how to do
it, but under the link here is an example where both x and y are plotted.

https://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type

As far as putting log on both axis - log scales are not built-in to
Chartist, but we're using a log scale through some implementation of
AutoScaleAxis that gets pluggedin - the implementation is in
lib/chartist-logaxis.js - if we're lucky, maybe that can same technique can
be applied on both x and y axes.

**Comment by davidebbo** [comment]
That sample looks very promising, thanks!

**Comment by davidbau** [comment]
Whoa that is so cool!!!!!  I have been playing with your PR and it is pretty awesome to be able to put smaller nearby localities on the same plot as South Korea or China or Italy.

![image](https://user-images.githubusercontent.com/3458792/79055855-50855580-7c1e-11ea-91eb-d64723eb356f.png)

It very clearly tells a policy story.  While it's good to be like S Korea, do not be like Japan.

http://localhost:8000/#/?include=Italy%3BS%20Korea%3BJapan%3BSpain%3BChina&ratio=3%2F5&stat=growth&advanced=1

**Comment by davidebbo** [comment]
Glad it's working well! Have you played with https://aatishb.com/covidtrends/ as well? It's nice that is has the animation over time. OTOH, we have far more flexibility is terms of localities and other tweaks. And nice colors :)

**Comment by davidbau** [comment]
Yeah the animation is very cool.  And also pretty useful in this case.

**Comment by davidbau** [comment]
Merged and pushed.  Thanks again @davidebbo!!!
