### ISSUE TITLE
Normalize location names and formats between CDS and JHU

### ISSUE THREAD

**Issue by davidbau** [davidbau/covid-19-chart#34]
CDS is doing an increasingly good job... To merge data sources and to support things like population normalization, we need to normalize location names and data formats between CDS and JHU and us.

Our conventions (and conversions from JHU) are encoded in `lib/flatten.js` (exercised in `test_csse.js`).  Each locality is either a country, "state", or "county", and is named as a suffix of"[county], [state], [country]" except in the US where we drop the country and just call it "[county], [state]".  US States are all called by two-letter abbreviations.

And county names follow the JHU convention of not saying "County" at the end (maybe we should change this for clarity).

We should have 
* a set of functions to normalize locality names that can convert from CDS locations
* a function to load CDS data into the same format as `lib/flatten.js` creates for CSSE data.
* a function to _merge_ CDS and CSSE timeseries data (and maybe note the provenance of each point meanwhile).   Simple heuristic: take the maximum value reported by either source on any given day.  Since reported stats are cumulative, this is robust.
* then we need to change the plotting code to consume this flattened format.

**Comment by dmaymudes** [comment]
I normalized the names in the population file so at least for countries, US states, and US counties they match what the graph data uses and setting norm=permillion appears to work for the cases I tested.

the timeseries-byLocation.json file now has more entries than it used to, so there are now 9187 entries with populations and 824 without.

It would no longer be a terrible idea to accept this pull request, but let me know if you want further changes.

(or accept it and then make them yourself, if you'd rather)

**Comment by davidbau** [comment]
This is done in the `merged_feeds` branch 0f64f6655a5f75f9ad9bfcf0aafff9cdd93c8c8e, but the results are not satisfying, because the CDS data quality is too low.  In particular, their counts of NY and NJ are way off, and they report one day earlier than everybody else, so merging corrupts the unified feed.

Closing as won't fix for now.
