### ISSUE TITLE
Chart doesn't show locality name when choosing an absolute start time

### ISSUE THREAD

**Issue by davidebbo** [davidbau/covid-19-chart#37]
With relative starts (e.g. >= 30), the locality is displayed on the right side of each line. For some reason, this doesn't happen with absolute start times (e.g. 3/23/2020).

**Comment by davidbau** [comment]
Fixed with 2ea8ff2c35f56a9c9a3537df44c470e8fa5e4cd4

**Comment by davidebbo** [comment]
Thanks, it looks pretty good with 10 series. Not so much with 100, but that's generally messy anyway.
