### ISSUE TITLE
Apply start rule to population-normalized data (not unnormalized)

### ISSUE THREAD

**Issue by joshuahhh** [davidbau/covid-19-chart#44]
I'm not 100% sure about this, but...

When viewing population-normalized data, a >=N start rule should apply to the normalized series, not the unnormalized ones. That is, it should be interpreted as ">=N per-million".

Why?
* This would make the normalized plots line up at the bottom-left, as they do in unnormalized mode.
* More substantively: I assume that the role of the ">=N start rule" is to imagine giving different countries/states the same "initial condition", to see how their paths diverge from that point. When you're in the per-million view, you are adopting a model where the "condition" of a country/state is the proportion of the state with confirmed cases or deaths, so equal proportions should be your definition of equal "initial conditions".

I'd be happy to make the change, if you felt that it would be helpful! (I would also adjust the ">=N" options to be more appropriate to "/pop" mode, when it is selected.)

Thanks a bunch.

**Comment by davidbau** [comment]
i agree, i think that will be an improvement, to have some ">=100/m" etc options that are available in pop mode.

**Comment by davidbau** [comment]
And when flipping between /pop and non-pop modes, it makes sense to automatically flip between >=100 to >=100/mil etc.  @joshuahhh if you want to make a pull request, it's very appreciated!

**Comment by davidbau** [comment]
Thanks @dmaymudes!  Pushed the fix.
