### ISSUE TITLE
Add option to plot statistics in terms of population density.

### ISSUE THREAD

**Issue by davidbau** [davidbau/covid-19-chart#5]
We should add an option to plot statistics in terms of population density.

This might reveal, for example, the terribly high rates of infection in Colorado springs, which are not revealed with currently graphed stats.

The coronadatascraper feed comes with by-county population information, and so could be done as part of #2  and #3.

**Comment by davidbau** [comment]
Recommendation from @cbentzel:

https://twitter.com/isfBob/status/1243334814163320832/photo/1

**Comment by davidbau** [comment]
Thanks @dmaymudes!   This improvement is now pushed to the live site, with a menu to go with it.

**Comment by davidebbo** [comment]
Can we improve the menu item text? 'norm' and 'none/first/pop' are quite meaningless for someone without context. I still don't know what 'first' means.

**Comment by davidbau** [comment]
Good point.  Opened issue #41.
