### ISSUE TITLE
New York total death toll going down on 4/6

### ISSUE THREAD

**Issue by davidebbo** [davidbau/covid-19-chart#50]
https://covid19chart.org/#/?top=0&include=NY&series=deaths&start=4%2F1%2F20&scale=linear&advanced=1

I assume this is a problem with the data source. Either that or zombies.

![image](https://user-images.githubusercontent.com/556238/79033333-47cf4980-7b62-11ea-84bb-23224bda8894.png)

**Comment by davidbau** [comment]
Yes, there is a weird thing in the JHU CSSE data - every death is in a county, but there is also an "Unassigned" county in each state, presumably for deaths that are counted at the state level without being counted at the county level.   Starting around 4/6, "Unassigned" deaths have been subtracted for dramatically in NY without assigning those deaths to other counties.  Not sure what is going on with that.

Maybe we should compare to the NY Times data feed to reconcile.

**Comment by davidebbo** [comment]
Another quirk I noticed is that all the NYC numbers are reported under NY county (which is supposed to be just Manhattan). And then the numbers for the other 4 boroughs/counties are all zeros. I guess they decided to count things that way and the per-county numbers just don't exist.

**Comment by davidbau** [comment]
Looks like JHU CSSE has retroactively fixed the Apr 6 negative numbers, so the plot looks good now.

Also - @dmaymudes and I have fixed the population numbers for NYC to match the merged reporting of the five boroughs (each a separate county within the city).

Closing as fixed!
