### ISSUE TITLE
Selection of top N could be improved

### ISSUE THREAD

**Issue by dmaymudes** [davidbau/covid-19-chart#56]
NY is chosen as the "top state" even if a graph starts on 6/1:

https://covid19chart.org/#/?advanced=-4&start=6%2F1%2F20&top=1&stat=daily

when from 

https://covid19chart.org/#/?advanced=-4&start=6%2F1%2F20&top=10&stat=daily

it clearly shouldn't be.

**Comment by davidebbo** [comment]
Seems it was just a silly bug in the delta check.

**Comment by davidebbo** [comment]
@davidbau would you mind reviewing and getting this in? Hopefully a very straightforward change. Thanks!
