### ISSUE TITLE
Consider changing the default view away from total cases

### ISSUE THREAD

**Issue by dmaymudes** [davidbau/covid-19-chart#59]
Maybe there's no perfect answer for everybody, but I think changing the default view to

start=4%2F1%2F20&stat=7day

might make sense.

I also tend to switch to "scale=linear&norm=pop&top=25"

at least that last shouldn't be necessary once #56 and #57 is fixed.

**Comment by davidbau** [comment]
I've updated defaults now.  Hopefully more useful.

**Comment by davidebbo** [comment]
Not directly related, but what I don't like about the pop view is that it doesn't let you see the actual underlying numbers. e.g. in the default view using 7days, hovering shows something like "FL 7/31/20 (470386) 458.01 per million", where 470386 is the **total** and not the 7day number.
